version: '3.8'

services:
  romashka:
    build: ./romashka
    depends_on:
      - volan

  repair:
    build: ./repair
    depends_on:
      - volan

  security:
    build: ./security
    depends_on:
      - volan
      
  volan:
    build: ./volan
    depends_on:
      - grif

  grif:
    build: ./grif
    depends_on:
      - kollektiv
  kollektiv:
    build: ./kollektiv
    ports:
      - "8002:8002"