version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.0
    container_name: zookeeper
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    ports:
     - "2181:2181"

  broker:
    image: confluentinc/cp-kafka:7.2.0
    container_name: broker
    ports:
      - "9092:9092"
    expose:
     - "29092"
    depends_on:
      - zookeeper
    env_file: ./broker/config/.env

  monitor:
    build: ./monitor
    entrypoint:
      - bash
      - -c
      - |
        echo 'Giving Kafka a bit of time to start up…'
        sleep 25
        python start.py /shared/config.ini
    container_name: monitor
    environment:
      - MODULE_NAME=monitor
    volumes:
      - ./shared:/shared

  video-service:
    build: ./romashka/video-service
    entrypoint:
      - bash
      - -c
      - |
        echo 'Giving Kafka a bit of time to start up…'
        sleep 25
        python start.py /shared/config.ini
    container_name: video-service
    environment:
      - MODULE_NAME=video-service
    volumes:
      - ./shared:/shared
    ports:
      - 8000:8000

  telemetry:
    build: ./romashka/telemetry
    entrypoint:
      - bash
      - -c
      - |
        echo 'Giving Kafka a bit of time to start up…'
        sleep 25
        python start.py /shared/config.ini
    container_name: telemetry
    environment:
      - MODULE_NAME=telemetry
    volumes:
      - ./shared:/shared
    ports:
      - 8001:8001

  data-collector:
    build: ./romashka/data-collector
    entrypoint:
      - bash
      - -c
      - |
        echo 'Giving Kafka a bit of time to start up…'
        sleep 25
        python start.py /shared/config.ini
    container_name: data-collector
    environment:
      - MODULE_NAME=data-collector
    volumes:
      - ./shared:/shared
    ports:
      - 8002:8002

  validator:
    build: ./romashka/validator
    entrypoint:
      - bash
      - -c
      - |
        echo 'Giving Kafka a bit of time to start up…'
        sleep 25
        python start.py /shared/config.ini
    container_name: validator
    environment:
      - MODULE_NAME=validator
    volumes:
      - ./shared:/shared
    ports:
      - 8003:8003