version: '3.8'

services:
  romashka:
    build: ./romashka
    depends_on:
      - volan
    networks:
      - kollektiv_net

  volan:
    build: ./volan
    depends_on:
      - grif
    networks:
      - kollektiv_net

  grif:
    build: ./grif
    depends_on:
      - kollektiv
    networks:
      - kollektiv_net

  kollektiv:
    build: ./kollektiv
    ports:
      - "8002:8002"
    networks:
      - kollektiv_net

networks:
  kollektiv_net:
    driver: bridge